version: '3.8'

services:
  backend:
    build: ./backend
    # command: sleep infinity
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env


  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  frontend:
    build: ./frontend
    # command: sleep infinity
    command: npm run start --host=0.0.0.0
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/frontend/node_modules
    ports:
      - 4200:4200
    depends_on:
      - db



volumes:
  postgres_data:
  node_modules: